name: Update Time

on:
  schedule:
    - cron: "*/5 * * * *" # Update setiap 5 menit
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Jalankan script untuk update waktu
        run: |
          node update_time.js

      - name: Commit dan Push Perubahan
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add TIME.md
          git commit -m "Update waktu otomatis"
          git push
